minimum_pre_commit_version: "4.0.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: ^node_modules/

  - repo: local
    hooks:
      - id: project-health-quick
        name: project-health-quick
        entry: make lint
        language: system
        pass_filenames: false
      - id: python-core-typecheck
        name: python-core-typecheck
        entry: make typecheck
        language: system
        pass_filenames: false
